version: '3'


services:
  app:
    build: .
    ports:
      - "8080:8080" 
    # define entrypoint and using reload flag for development
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    # volumes allow us to map external places of storage to place in our docker container
    volumes:
      -